### ISSUE TITLE
EVCC AC charge simulator

### ISSUE THREAD

**Issue by macellari-mac** [SwitchEV/josev#7]
Hi,
I'm testing iso15118 EVCC but it seems that it only works in DC mode.
I cannot find documentation explaining how to set the EVCC to work in AC mode.
If I setup the SECC to work only in AC mode then the EVCC stops in early phases.
If I setup the SECC to work in both AC/DC mode then the EVCC simulator goes on in DC mode.

Can you help please?
Thanks
Lucio

**Comment by shalinnijel2** [comment]
Hi Lucio,

Apologies for the late reply - didn't spot this issue raised here.

This is the line where the EVCC returns the energy transfer mode:
https://github.com/SwitchEV/iso15118/blob/4d78789bd4ad5dd7de26c92f9f85f775d30eb438/iso15118/evcc/controller/simulator.py#L167

To get the ev simulator to run in AC, you could perhaps change the method to:
```
return EnergyTransferModeEnum.AC_THREE_PHASE_CORE
```
Another item that might also be interesting in this context: There is a ticket being worked on at the moment that helps run evcc simulator with a config. 
https://github.com/SwitchEV/iso15118/pull/172
